# Generated by Django 3.1.6 on 2021-02-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, error_messages={'invalid': 'Make sure you wrote at most 200 chars!'}, max_length=200),
        ),
    ]
