# Generated by Django 3.1.6 on 2021-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='postimages/'),
            preserve_default=False,
        ),
    ]
