# Generated by Django 3.1.6 on 2021-02-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
